ARG ARCH
FROM ${ARCH}/postgres:11-alpine

ARG QEMU_ARCH
COPY tmp/qemu-${QEMU_ARCH}-static /usr/bin/qemu-${QEMU_ARCH}-static
RUN chmod +x /usr/bin/qemu-${QEMU_ARCH}-static

ARG GOSU_ARCH
COPY tmp/gosu-${GOSU_ARCH} /usr/bin/gosu
RUN chmod +x /usr/bin/gosu

RUN apk add --update iputils
RUN apk add --update htop

COPY ./setup-replica.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["gosu", "postgres", "postgres"]
