ARG ARCH
ARG POSTGRES_BASE
FROM ${ARCH}/${POSTGRES_BASE}

ARG ARCH
ARG POSTGRES_BASE
ENV BASE_IMAGE=${ARCH}/${POSTGRES_BASE}

ARG QEMU_ARCH
COPY tmp/qemu-${QEMU_ARCH}-static /usr/bin/qemu-${QEMU_ARCH}-static
RUN chmod +x /usr/bin/qemu-${QEMU_ARCH}-static

RUN apk add --update htop

COPY ./setup-primary.sh /docker-entrypoint-initdb.d/setup-primary.sh
RUN chmod 0666 /docker-entrypoint-initdb.d/setup-primary.sh
